### PR TITLE
fix: improve peer reconciliation

### LINKED ISSUE #1871: Improve the reconciliation between peers when calling `addPeer`
Currently we are facing an issue in production when the connection between edge servers drops and they try to reconnect.

This happens because the reconciliantion system implemented inside `addPeer` is quite naive:
- https://github.com/garden-co/jazz/blob/main/packages/cojson/src/sync.ts#L321

We could improve it by:
- Reviewing carefully the messages sent for each entry state, and do different things when re-connection to a pre-existing peer
- Excecute the reconcilation with low priority, to not bring down the core server

### PR DESCRIPTION
**Pull request by gdorsi**
fixes #1871

### CODE REVIEW

File: packages/cojson/src/sync.ts [hunk 1]
```diff
@@ -285,27 +291,85 @@ export class SyncManager {
...
+  }
+
+  async addPeer(peer: Peer) {
     const prevPeer = this.peers[peer.id];
     const peerState = new PeerState(peer, prevPeer?.knownStates);
     this.peers[peer.id] = peerState;
 
     if (prevPeer && !prevPeer.closed) {
       prevPeer.gracefulShutdown();
+      await prevPeer.processMessages?.catch((e) => {});
```
Comment (gdorsi) [inline packages/cojson/src/sync.ts]: We need to wait for the previous peer to process all the incoming messages before starting to process the new  peer messages.

This is probably why, on frequent reconnections, the sync server starts to have troubles.

File: packages/cojson/src/sync.ts [hunk 2]
```diff
@@ -285,27 +291,85 @@ export class SyncManager {
...
         type: "COMBINE_WITH",
-        id,
+        id: coValue.id,
         value: coValue.knownState(),
       });
     }
   }
 
-  addPeer(peer: Peer) {
+  async startPeerReconciliation(peer: PeerState) {
```
Comment (gdorsi) [inline packages/cojson/src/sync.ts:240]: Before we were sending the content without waiting for the `known` state from the server.

Done some changes so we just send a `load` request for each available coValue to the server.

Added some logic to make the server request the content if they notice that they miss some content from the client.

The downside is that we now wait for the server response before sending the content, but we should send less messages around (in theory)

File: packages/cojson/src/sync.ts (hunk 1 above)
Comment (gdorsi) [reply packages/cojson/src/sync.ts]: Quick fix, doesn't handle more than one peers in line to be added.

Will improve in the final version of the PR

File: packages/cojson/src/tests/sync.test.ts [hunk 3]
```diff
@@ -654,32 +662,228 @@ test("When we connect a new server peer, we try to sync all existing coValues to
...
+      msg: {
+        action: "known",
+        asDependencyOf: undefined,
+        ...group.core.knownState(),
+      },
+    },
+    {
+      from: "client",
+      msg: map.core.newContentSince(undefined)?.[0],
+    },
```
Comment (gdorsi) [inline packages/cojson/src/tests/sync.test.ts]: We send the same content twice 🤔

File: packages/cojson/src/tests/sync.test.ts [hunk 4]
```diff
@@ -654,32 +662,228 @@ test("When we connect a new server peer, we try to sync all existing coValues to
...
+        ...map.core.knownState(),
+      },
+    },
+    {
+      from: "client",
+      msg: {
+        action: "content",
+        ...map.core.newContentSince(knownStateBefore)?.[0],
+      },
+    },
```
Comment (gdorsi) [inline packages/cojson/src/tests/sync.test.ts]: We send the same content twice 🤔

File: packages/jazz-tools/src/coValues/account.ts [hunk 5]
```diff
@@ -288,11 +288,15 @@ export class Account extends CoValueBase implements CoValue {
...
-    return this.create<A>({
+    const account = await this.create<A>({
       creationProps: options.creationProps,
       crypto: as._raw.core.node.crypto,
       peersToLoadFrom: [connectedPeers[0]],
     });
+
+    await account.waitForAllCoValuesSync();
+
+    return account;
```
Comment (gdorsi) [inline packages/jazz-tools/src/coValues/account.ts:299]: Needed this change because the content reconciliation now requires more than one roundtrip.

File: packages/cojson/src/sync.ts [hunk 6]
```diff
@@ -189,65 +190,6 @@ export class SyncManager {
...
-      this.trySendToPeer(peer, {
-        action: "load",
-        ...coValue.knownState(),
-      }).catch((e: unknown) => {
-        logger.error("Error sending load", { err: e });
-      });
-    }
-  }
-
-  async tellUntoldKnownStateIncludingDependencies(
```
Comment (gdorsi) [inline packages/cojson/src/sync.ts:228]: These two methods have been optimized away. See below.

File: packages/cojson/src/PeerState.ts [hunk 7]
```diff
@@ -150,4 +153,35 @@ export class PeerState {
     this.peer.outgoing.close();
     this.closed = true;
   }
+
+  async processIncomingMessages(callback: (msg: SyncMessage) => Promise<void>) {
```
Comment (gdorsi) [inline packages/cojson/src/PeerState.ts:157]: Moved this logic inside PeerState to handle the tracking of incomingMessagesProcessingPromise internally

File: packages/cojson/src/sync.ts [hunk 8]
```diff
@@ -189,56 +190,35 @@ export class SyncManager {
...
       coValue
         .getDependedOnCoValues()
-        .map((dependentCoID) =>
-          this.tellUntoldKnownStateIncludingDependencies(
-            dependentCoID,
-            peer,
-            asDependencyOf || id,
-          ),
-        ),
+        .map((id) => this.sendNewContentIncludingDependencies(id, peer)),
```
Comment (gdorsi) [inline packages/cojson/src/sync.ts:208]: Refactored to send the `known` message inside `sendNewContentIncludingDependencies`

This way we can optimize away the known message when we have new content to sync.

File: packages/cojson/src/sync.ts [hunk 9]
```diff
@@ -189,56 +190,35 @@ export class SyncManager {
...
+      peer.optimisticKnownStates.get(id),
     );
 
-    if (!peer.toldKnownState.has(id)) {
+    if (newContentPieces) {
+      for (const piece of newContentPieces) {
+        this.trySendToPeer(peer, piece).catch((e: unknown) => {
+          logger.error("Error sending content piece", { err: e });
+        });
+      }
```
Comment (gdorsi) [inline packages/cojson/src/sync.ts:220]: Simplified this part, before:
```ts
     const optimisticKnownStateBefore =
        peer.optimisticKnownStates.get(id) || emptyKnownState(id);

      const sendPieces = async () => {
        let lastYield = performance.now();
        for (const [_i, piece] of newContentPieces.entries()) {
          this.trySendToPeer(peer, piece).catch((e: unknown) => {
            logger.error("Error sending content piece", { err: e });
          });

          if (performance.now() - lastYield > 10) {
            await new Promise<void>((resolve) => {
              setTimeout(resolve, 0);
            });
            lastYield = performance.now();
          }
        }
      };

      sendPieces().catch((e) => {
        logger.error("Error sending new content piece, retrying", { err: e });
        peer.optimisticKnownStates.dispatch({
          type: "SET",
          id,
          value: optimisticKnownStateBefore ?? emptyKnownState(id),
        });
        return this.sendNewContentIncludingDependencies(id, peer);
      });
```

Removed the scheduling code, now we have scheduling inside the outgoing messages.
Also the error management was quite unreachable.

File: packages/cojson/src/sync.ts [hunk 10]
```diff
@@ -248,66 +228,101 @@ export class SyncManager {
...
+      }).catch((e: unknown) => {
+        logger.error("Error sending load", { err: e });
       });
     }
   }
 
-  addPeer(peer: Peer) {
+  nextPeer: Map<PeerID, Peer> = new Map();
+
+  async addPeer(peer: Peer) {
```
Comment (gdorsi) [inline packages/cojson/src/sync.ts:311]: Major fix here.

Before we weren't waiting for the previous peer to completely close and we lacked support multiple subsequent reconnections.

File: packages/cojson/src/sync.ts [hunk 11]
```diff
@@ -403,30 +402,23 @@ export class SyncManager {
...
 
       if (eligiblePeers.length === 0) {
-        // If the load request contains a header or any session data
-        // and we don't have any eligible peers to load the coValue from
-        // we try to load it from the sender because it is the only place
-        // where we can get informations about the coValue
-        if (msg.header || Object.keys(msg.sessions).length > 0) {
-          entry.loadFromPeers([peer]).catch((e) => {
-            logger.error("Error loading coValue in handleLoad", { err: e });
-          });
```
Comment (gdorsi) [inline packages/cojson/src/sync.ts:422]: Removed this part because sending a `known` message gives us what we need for this situation (content syncing) and there is no need for requesting the CoValue load.

File: packages/cojson/src/sync.ts [hunk 12]
```diff
@@ -461,27 +448,23 @@ export class SyncManager {
...
         id: msg.id,
         header: false,
         sessions: {},
       });
     }
-
-    if (entry.state.type === "available") {
-      await this.tellUntoldKnownStateIncludingDependencies(msg.id, peer);
-      await this.sendNewContentIncludingDependencies(msg.id, peer);
-    }
```
Comment (gdorsi) [inline packages/cojson/src/sync.ts:493]: Moved up in the else/if

File: packages/cojson/src/sync.ts [hunk 13]
```diff
@@ -493,31 +476,6 @@ export class SyncManager {
       value: knownStateIn(msg),
     });
 
-    if (entry.state.type === "unknown" || entry.state.type === "unavailable") {
-      if (msg.asDependencyOf) {
```
Comment (gdorsi) [inline packages/cojson/src/sync.ts:506]: This was very likely a workaround.

I think it's not needed anymore

File: packages/cojson/src/sync.ts [hunk 14]
```diff
@@ -729,10 +686,8 @@ export class SyncManager {
       if (peer.erroredCoValues.has(coValue.id)) continue;
 
       if (peer.optimisticKnownStates.has(coValue.id)) {
-        await this.tellUntoldKnownStateIncludingDependencies(coValue.id, peer);
         await this.sendNewContentIncludingDependencies(coValue.id, peer);
       } else if (peer.isServerOrStoragePeer()) {
-        await this.subscribeToIncludingDependencies(coValue.id, peer);
         await this.sendNewContentIncludingDependencies(coValue.id, peer);
```
Comment (gdorsi) [inline packages/cojson/src/sync.ts:717]: Before https://github.com/garden-co/jazz/pull/1741/files we needed to send a `load` message to the server to trigger the load of the CoValue from storage before sending content.

Now it's not required anymore.

Also the subscription is handled inside sendNewContentIncludingDependencies

File: packages/cojson/src/tests/sync.load.test.ts [hunk 15]
```diff
@@ -0,0 +1,336 @@
...
+      ),
+    ).toMatchInlineSnapshot(`
+      [
+        "client -> LOAD Map sessions: empty",
+        "server -> CONTENT Group header: true new: After: 0 New: 3",
+        "client -> KNOWN Group sessions: header/3",
+        "server -> CONTENT Map header: true new: After: 0 New: 1",
+        "client -> KNOWN Group sessions: header/3",
+        "client -> KNOWN Map sessions: header/1",
+        "client -> KNOWN Map sessions: header/1",
```
Comment (gdorsi) [inline packages/cojson/src/tests/sync.load.test.ts:44]: Still having a duplicated KNOWN message here, in the end as ACK. 🤔

File: packages/cojson/src/tests/sync.test.ts [hunk 16]
```diff
@@ -33,454 +40,6 @@ beforeEach(async () => {
   jazzCloud = setupSyncServer();
 });
 
-test("Node replies with initial tx and header to empty subscribe", async () => {
```
Comment (gdorsi) [inline packages/cojson/src/tests/sync.test.ts:36]: Replaced these tests with the ones inside `sync.load` and `sync.peerReconciliation`

File: packages/jazz-tools/src/tests/groupsAndAccounts.test.ts [hunk 17]
```diff
@@ -155,7 +155,7 @@ describe("Group inheritance", () => {
     const mapAsReaderAfterUpdate = await TestMap.load(mapInGrandChild.id, {
       loadAs: reader,
     });
-    expect(mapAsReaderAfterUpdate?.title).toBe("In Grand Child");
+    expect(mapAsReaderAfterUpdate).toBe(null);
```
Comment (gdorsi) [inline packages/jazz-tools/src/tests/groupsAndAccounts.test.ts:158]: This is actually what should happen when the user lose access to the map.

Probably because of the optimizations it happens with less event loop iterations.

File: tests/e2e/tests/RetryUnavailable.test.ts [hunk 18]
```diff
@@ -21,8 +21,6 @@ test.describe("Retry unavailable states", () => {
       timeout: 20_000,
     });
 
-    await setTimeout(1000);
```
Comment (gdorsi) [inline tests/e2e/tests/RetryUnavailable.test.ts:24]: Had to remove this timeout, probably because since now the peer reconciliation doesn't send the content directly it takes more time.

File: packages/cojson-storage-sqlite/src/tests/sqlite.test.ts [hunk 19]
```diff
@@ -0,0 +1,321 @@
...
+  expect(map2.get("hello")).toBe("world");
+
+  expect(
+    toSimplifiedMessages(
+      {
+        Map: map.core,
+        Group: group.core,
+      },
+      node2Sync.messages,
+    ),
```
Comment (gdorsi) [inline packages/cojson-storage-sqlite/src/tests/sqlite.test.ts:115]: Created a test utility to be able to use snapshot tests against the sync messages.

I've basically summarized all the important bits and removed all the randomized ids and sessions

**Review by emmyoh — COMMENTED** [review]
Your comments (both in code and PR) were super useful. No feedback on how to better document this 👍

File: packages/cojson-storage-sqlite/src/tests/sqlite.test.ts (hunk 19 above)
Comment (aeplay) [reply packages/cojson-storage-sqlite/src/tests/sqlite.test.ts:115]: love it

File: packages/cojson-storage-sqlite/src/tests/sqlite.test.ts [hunk 20]
```diff
@@ -0,0 +1,321 @@
...
+  ).toMatchInlineSnapshot(`
+    [
+      "client -> LOAD Map sessions: empty",
+      "storage -> KNOWN Group sessions: header/3",
+      "storage -> CONTENT Group header: true new: After: 0 New: 3",
+      "client -> KNOWN Group sessions: header/3",
+      "storage -> KNOWN Map sessions: header/1",
+      "storage -> CONTENT Map header: true new: After: 0 New: 1",
```
Comment (gdorsi) [inline packages/cojson-storage-sqlite/src/tests/sqlite.test.ts:123]: We can probably optimize away those `storage -> KNOWN` messages because the content is enough to update the knownState

File: packages/cojson/src/sync.ts (hunk 10 above)
Comment (aeplay) [reply packages/cojson/src/sync.ts:311]: bravo!

File: packages/jazz-tools/src/coValues/account.ts (hunk 5 above)
Comment (aeplay) [reply packages/jazz-tools/src/coValues/account.ts:299]: thanks for catching it

File: packages/cojson/src/sync.ts [hunk 21]
```diff
@@ -257,66 +237,101 @@ export class SyncManager {
...
-    const coValue = this.local.expectCoValueLoaded(id);
+  async startPeerReconciliation(peer: PeerState) {
+    const coValuesOrderedByDependency: CoValueCore[] = [];
 
-    await Promise.all(
-      coValue
-        .getDependedOnCoValues()
-        .map((id) => this.sendNewContentIncludingDependencies(id, peer)),
-    );
+    const requested = new Set<string>();
```
Comment (aeplay) [inline packages/cojson/src/sync.ts]:
```suggestion
    const gathered = new Set<string>();
```

(`requested` sounds like you're already doing some syncing, when you're just gathering & ordering them)

File: packages/cojson/src/sync.ts [hunk 22]
```diff
@@ -257,66 +237,101 @@ export class SyncManager {
...
 
-    const newContentPieces = coValue.newContentSince(
-      peer.optimisticKnownStates.get(id),
-    );
+    const buildOrderedCoValueList = (coValue: CoValueCore) => {
+      if (requested.has(coValue.id)) {
```
Comment (aeplay) [inline packages/cojson/src/sync.ts]:
```suggestion
      if (gathered.has(coValue.id)) {
```

File: packages/cojson/src/sync.ts [hunk 23]
```diff
@@ -257,66 +237,101 @@ export class SyncManager {
...
-      const optimisticKnownStateBefore =
-        peer.optimisticKnownStates.get(id) || emptyKnownState(id);
-
-      const sendPieces = async () => {
-        let lastYield = performance.now();
-        for (const [_i, piece] of newContentPieces.entries()) {
-          this.trySendToPeer(peer, piece).catch((e: unknown) => {
-            logger.error("Error sending content piece", { err: e });
-          });
+      requested.add(coValue.id);
```
Comment (aeplay) [inline packages/cojson/src/sync.ts]:
```suggestion
      gathered.add(coValue.id);
```

**Review by aeplay — APPROVED** [review]
Just have one variable rename suggestion, otherwise all LGTM! Thank you very much

**Review by emmyoh — APPROVED** [review]
