### PR TITLE
fix: handle Clerk expiration and fix logout

### LINKED ISSUE #1658: Auth clerk: calling Clerk.signOut from doesn't logout the user from Jazz
Reported here: https://discord.com/channels/1139617727565271160/1313981497010552852/1349696811652350035

> I think I needed to call both the `logOut` function from `useAccount` hook and also the `signOut` function from the `useAuth` hook. Now it works.

The user should only call `logOut`, and not `signOut` also. Trying to reproduce.

Maybe somehow related to @boorad reporting the need to tap the logout button twice to actually logout ?

### LINKED ISSUE #1802: Jazz React `useIsAuthenticated()` does not keep in sync with Clerk
After logging in with the Jazz Clerk integration, when the Clerk auth session has expired (after 7 days on the free tier), Jazz's `useIsAuthenticated()` does not respect the new Clerk logged out state. This can be observed when using the `<UserButton />` component from @clerk/clerk-react – 7 days after logging in, the `<UserButton />` becomes disabled despite `useIsAuthenticated()` returns `true`.

# To reproduce

- Set up a Jazz React app using the Clerk example
- Place the `<UserButton />` in a post-auth part of the app
- Sign on the app up with a user
- Wait 7 days (providing session duration is set to 7 days in the Clerk dashboard)
- Notice that the `<UserButton />` component is no longer accessible

# Expectation

I would expect the Jazz Session to monitor Clerk's logged-in status and revert to the logged-out state when the Clerk auth session expires.

### PR DESCRIPTION
**Pull request by gdorsi**
fixes #1658
fixes #1802 

This PR turns upside down the Clerk auth management, making `clerk` our source of truth for the auth state.

This improves:
- The logout flow is much more simple. We clear the credentials when the user is not authenticated anymore in clerk.
- SignOut made from Clerk now works
- When the Clerk session expires the user is logged out from Jazz

### CODE REVIEW

File: examples/chat-rn-expo-clerk/app/_layout.tsx [hunk 1]
```diff
@@ -33,6 +44,17 @@ export default function RootLayout() {
...
+  useEffect(() => {
+    if (fontsLoaded) {
+    } else {
+      SplashScreen.preventAutoHideAsync();
+    }
+  }, [fontsLoaded]);
+
+  if (!fontsLoaded) {
+    return null;
+  }
```
Comment (gdorsi) [inline examples/chat-rn-expo-clerk/app/_layout.tsx:56]: Picked these changes from #1848 as before the user wasn't redirected to the auth screen on logout.

File: packages/jazz-auth-clerk/src/index.ts [hunk 2]
```diff
@@ -37,13 +38,47 @@ export class JazzClerkAuth {
...
+    return clerkClient.addListener((event) => {
+      const user = (event as Pick<MinimalClerkClient, "user">).user ?? null;
+
+      if (!isClerkAuthStateEqual(previousUser, user) || this.isFirstCall) {
+        this.onClerkUserChange({ user });
+        previousUser = user;
+        this.isFirstCall = false;
+      }
+    });
+  }
```
Comment (gdorsi) [inline packages/jazz-auth-clerk/src/index.ts:70]: Moved the logic from the framework adapters here to reduce duplicates and make it more testable.

File: packages/jazz-auth-clerk/src/index.ts [hunk 3]
```diff
@@ -37,13 +38,47 @@ export class JazzClerkAuth {
...
+
+  registerListener(clerkClient: MinimalClerkClient) {
+    let previousUser: MinimalClerkClient["user"] | null =
+      clerkClient.user ?? null;
+
+    // Need to use addListener because the clerk user object is not updated when the user logs in
+    return clerkClient.addListener((event) => {
+      const user = (event as Pick<MinimalClerkClient, "user">).user ?? null;
+
+      if (!isClerkAuthStateEqual(previousUser, user) || this.isFirstCall) {
```
Comment (gdorsi) [inline packages/jazz-auth-clerk/src/index.ts:64]: This is part of the bugfix, we now call `onClerkUserChange` only on the first trigger or when the auth state really changes.
