### PR TITLE
fix: update WebAuthn challenge length to 20 bytes

### LINKED ISSUE #2974: Passkey login fails with keepassxc firefox extension
## Description

- `signUp("")` works correctly with KeePassXC firefox extension (passkey created and login)
- `logIn()` fails with the message "challenge is shorter than required minimum length"

## Clue

It seems that KeePassXC requires a Challenge that is ≥16 bytes for WebAuthn authentication.

## Message in the browser console

```
Done with lock
co_znWHGLBMX85CJ9yMiHQvCkZkoC3_0
co_znWHGLBMX85CJ9yMiHQvCkZkoC3_session_zivxftao7opN-tEP6CdL.js:33:484196
TypeError: challenge is shorter than required minimum length.
    checkErrors moz-extension://ee123b0b-2d53-4f49-a691-b5373b78d113/content/passkeys-utils.js:27
    buildCredentialRequestOptions moz-extension://ee123b0b-2d53-4f49-a691-b5373b78d113/content/passkeys-utils.js:106
    enablePasskeys moz-extension://ee123b0b-2d53-4f49-a691-b5373b78d113/content/passkeys-inject.js:79
    postMessageToExtension moz-extension://ee123b0b-2d53-4f49-a691-b5373b78d113/content/passkeys.js:90
    postMessageToExtension moz-extension://ee123b0b-2d53-4f49-a691-b5373b78d113/content/passkeys.js:74
    get moz-extension://ee123b0b-2d53-4f49-a691-b5373b78d113/content/passkeys.js:176
    Immutable 4
passkeys-utils.js:138:17
uncaught exception: NotAllowedError: lifetimeTimer has expiredpasskeys-inject.js:21:19
Uncaught (in promise) Error: Passkey creation aborted
    Immutable 4
Caused by: DOMException: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.-tEP6CdL.js:33:481442
```

### PR DESCRIPTION
**Pull request by joeinnes**
Fix TS issue (crypto.randomBytes allows SharedArrayBuffer-backed Uint8Arrays, but WebAuthn doesn't)

Fixes #2974 

# Description
Increases challenge length to 20 bytes, type fixes.

## Manual testing instructions
N/A

## Tests

- [ ] Tests have been added and/or updated
- [x] Tests have not been updated, because: Current behaviour is permitted by spec, and we are anyway mocking the browser in our tests, so unit testing this would only be testing our mock implementation.
- [ ] I need help with writing tests

## Checklist

- [ ] I've updated the part of the docs that are affected the PR changes
- [x] I've generated a changeset, if a version bump is required
- [ ] I've updated the jsDoc comments to the public APIs I've modified, or added them when missing

---

> [!NOTE]
> Switches WebAuthn challenges to 20-byte Uint8Arrays for both credential creation and retrieval, adding a patch changeset.
> 
> - **Auth (WebAuthn)**:
>   - `packages/jazz-tools/src/browser/auth/PasskeyAuth.ts`:
>     - `createPasskeyCredentials`: `challenge` now `new Uint8Array(this.crypto.randomBytes(20))` (was `this.crypto.randomBytes(20)`).
>     - `getPasskeyCredentials`: `challenge` now `new Uint8Array(this.crypto.randomBytes(20))` (was `Uint8Array.from([0, 1, 2])`).
> - **Changeset**:
>   - Adds `.changeset/rich-pillows-study.md` (patch for `jazz-tools`) noting increased passkey challenge length for compatibility.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 2c01529679000b54bd20ff11ecf1289d68cbe06b. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/jazz-tools/src/browser/auth/PasskeyAuth.ts [hunk 1]
```diff
@@ -122,7 +122,7 @@ export class BrowserPasskeyAuth {
     try {
       await navigator.credentials.create({
         publicKey: {
-          challenge: this.crypto.randomBytes(20),
+          challenge: new Uint8Array(this.crypto.randomBytes(20)),
```
Comment (gdorsi) [inline packages/jazz-tools/src/browser/auth/PasskeyAuth.ts:125]: nit: randomBytes already return a `Uint8Array`

**Review by gdorsi — APPROVED** [review]
Thanks for the quick turnaround!

File: packages/jazz-tools/src/browser/auth/PasskeyAuth.ts (hunk 1 above)
Comment (joeinnes) [reply packages/jazz-tools/src/browser/auth/PasskeyAuth.ts:125]: Yep, but the type for randomBytes allows a SharedArrayBuffer
