### PR TITLE
fix(inspector): CoMaps showing as table instead of grid

### LINKED ISSUE #1843: Inspector shows a table with undefined rows for a CoMap
Schema:
```ts
export class AccountRoot extends CoMap {
  dreams = co.ref(Dreams)
  dreams_archive = co.ref(DreamsArchive)
  preferences = co.ref(Preferences)
  settings = co.ref(Settings)
  user_dream_tags = co.ref(UserDreamTags)
}

export class BaseAccount extends Account {
  profile = co.ref(AccountProfile)
  root = co.ref(AccountRoot)
}
```

The inspector showing a table, when CoMaps should be grid view. There are also fields shown that are not from AccountRoot. They are from the settings field.

Image

### PR DESCRIPTION
**Pull request by trishalim**
This is how we're checking for Record-like CoMaps:

```
          const children = Object.values(snapshot).slice(0, 10);

          if (
            children.every(
              (c) => typeof c === "string" && c.startsWith("co_"),
            ) &&
            children.length > 3
          ) {
            extendedType = "record";
          }
```

It takes the first 10 fields, and if all these fields point to a reference (not a primitive), and if there are more than 3 fields, then it's considered a Record-like CoMap.

This is not correct because a Record-like CoMap can also have primitive values. And it also falsely identifies normal CoMaps as Records if all the fields are references, like the following:

```
export class AccountRoot extends CoMap {
  dreams = co.ref(Dreams)
  dreams_archive = co.ref(DreamsArchive)
  preferences = co.ref(Preferences)
  settings = co.ref(Settings)
  user_dream_tags = co.ref(UserDreamTags)
}
```

I've not found a way to detect Record-like CoMaps, so the fix is to remove this checking, and we'll show Records like a regular CoMap, which looks fine imo.

fixes #1843

### CODE REVIEW

File: packages/jazz-inspector/src/viewer/use-resolve-covalue.ts [hunk 1]
```diff
@@ -93,17 +93,8 @@ export async function resolveCoValue(
       extendedType = "account";
     } else if (isGroup(snapshot)) {
       extendedType = "group";
-    } else {
-      // This check is a bit of a hack
-      // There might be a better way to do this
-      const children = Object.values(snapshot).slice(0, 10);
-      if (
-        children.every((c) => typeof c === "string" && c.startsWith("co_")) &&
```
Comment (trishalim) [inline packages/jazz-inspector/src/viewer/use-resolve-covalue.ts:101]: If the type of the value of the record-like comap is a primitive and not a reference, then this becomes false.

File: packages/jazz-inspector/src/viewer/use-resolve-covalue.ts [hunk 2]
```diff
@@ -93,17 +93,8 @@ export async function resolveCoValue(
...
-        children.length > 3
```
Comment (trishalim) [inline packages/jazz-inspector/src/viewer/use-resolve-covalue.ts:102]: This doesn't make sense because you can have record-like comaps with less than 3 fields

**Review by aeplay — APPROVED** [review]

File: packages/jazz-inspector/src/viewer/use-resolve-covalue.ts [hunk 3]
```diff
@@ -93,17 +93,8 @@ export async function resolveCoValue(
...
-      ) {
-        extendedType = "record";
-      }
     }
+    // TODO: check for Record-like CoMaps
```
Comment (gdorsi) [inline packages/jazz-inspector/src/viewer/use-resolve-covalue.ts]: Currently there isn't a way to identify a Record-like CoMap and as you have mentioned in the PR description the current visualization looks fine.

So I would suggest to remove this TODO and if in the future we find issues for maps with many fields, do fixes for both normal maps and Record-like CoMap.

**Review by gdorsi — APPROVED** [review]
LGTM, thanks!

File: packages/jazz-inspector/src/viewer/use-resolve-covalue.ts (hunk 3 above)
Comment (gdorsi) [inline packages/jazz-inspector/src/viewer/use-resolve-covalue.ts]:
```suggestion
```

File: packages/jazz-inspector/src/viewer/use-resolve-covalue.ts [hunk 4]
```diff
@@ -139,17 +130,8 @@ function subscribeToCoValue(
...
-          if (
-            children.every(
-              (c) => typeof c === "string" && c.startsWith("co_"),
-            ) &&
-            children.length > 3
-          ) {
-            extendedType = "record";
-          }
         }
+        // TODO: check for Record-like CoMaps
```
Comment (gdorsi) [inline packages/jazz-inspector/src/viewer/use-resolve-covalue.ts]:
```suggestion
```
