### PR TITLE
fix: make checks on the discriminator field on z.discriminatedUnion more specific and less strict

### LINKED ISSUE #2372: Creating a coMap value with a z.optional(z.date()) field throws error when passing undefined as date.
I have this schema:

```ts
export const NotificationPayload = co.map({
  ...
  triggerDate: z.optional(z.date()),
});
```

when I try to create a new object without a date from it, I am getting an error: 

```ts
export async function sendNotificationPayload(
  triggerDate?: Date,
) {
    const payload = NotificationPayload.create(
      {
        //...
        triggerDate: triggerDate,
      },
      { owner: Group.create({ owner: sender }) }
    );
}
```

`Cannot read property 'toISOString' of undefined`

I am at jazz-expo 0.14.17

### PR DESCRIPTION
**Pull request by gdorsi**
fixes https://github.com/afanslau/repro-discriminated-union/pull/1/files

fixes #2372

### CODE REVIEW

File: packages/jazz-tools/src/implementation/zodSchema/unionUtils.ts [hunk 1]
```diff
@@ -11,19 +11,22 @@ export function schemaUnionDiscriminatorFor(
...
-      throw new Error(
-        "z.discriminatedUnion() of collaborative types with non-string discriminator value is not supported",
-      );
+
+    for (const value of field.values) {
+      if (typeof value !== "string" && typeof value !== "number") {
+        throw new Error(
+          "z.discriminatedUnion() of collaborative types with non-string or non-number discriminator value is not supported",
+        );
+      }
```
Comment (gdorsi) [inline packages/jazz-tools/src/implementation/zodSchema/unionUtils.ts:29]: Strict checks only on the main discriminator

File: packages/jazz-tools/src/implementation/zodSchema/unionUtils.ts [hunk 2]
```diff
@@ -46,49 +49,52 @@ export function schemaUnionDiscriminatorFor(
...
-          return (
-            (discriminatorDef._zod.def as z.core.$ZodLiteralDef).values[0] ===
-            discriminatorValue
-          );
-        });
-        if (remainingOptions.length === 1) {
-          return zodSchemaToCoSchema(remainingOptions[0]!);
+        }
+
+        if (match) {
```
Comment (gdorsi) [inline packages/jazz-tools/src/implementation/zodSchema/unionUtils.ts:92]: The first field that matches all the discriminators passes.

Any non-defined implicit discriminator is skipped in the check
