### PR TITLE
fix: hidden headings are showing in TOC

### LINKED ISSUE #1893: TOC is showing hidden headings
https://jazz.tools/docs/react-native/authentication/clerk

### PR DESCRIPTION
**Pull request by trishalim**
To test, compare the two:
- https://jazz-homepage-git-fix-toc-headings-gcmp.vercel.app/docs/react/inspector
- https://jazz-homepage-git-fix-toc-headings-gcmp.vercel.app/docs/svelte/inspector

closes #1893

### CODE REVIEW

File: homepage/homepage/lib/docMdxContent.tsx [hunk 1]
```diff
@@ -90,14 +90,38 @@ export async function getMdxWithToc(framework: string, slug?: string[]) {
   } = mdxSource;
 
   // Remove items that should not be shown for the current framework
-  const tocItems = (tableOfContents as Toc).filter(({ id }) =>
-    id && id in headingsFrameworkVisibility
-      ? headingsFrameworkVisibility[id]?.includes(framework)
-      : true,
```
Comment (trishalim) [inline homepage/homepage/lib/docMdxContent.tsx:96]: this filtering needed to be recursive

Comment (bensleveritt) [reply homepage/homepage/lib/docMdxContent.tsx:96]: Do you want to put this into a new issue?

**Review by bensleveritt — APPROVED** [review]
Nicely done, thanks!

File: homepage/homepage/lib/docMdxContent.tsx (hunk 1 above)
Comment (trishalim) [reply homepage/homepage/lib/docMdxContent.tsx:96]: It's already fixed
