### PR TITLE
 fix: server subscription when streaming from storage

### LINKED ISSUE #2584: Bug: streaming from storage triggers content download from the server peers

### PR DESCRIPTION
**Pull request by gdorsi**
### What this Does

To optimize the loading of large CoValue sessions, we split the content in many small blocks and we call it streaming.

Currently we have a bug when streaming content from storage, that leads to having content be pushed also from the sync server even thou it's available on storage.

In [this test for](https://github.com/garden-co/jazz/blob/feat/storage-api/packages/cojson/src/tests/sync.storage.test.ts#L304) example there should be no content sent from the server.

This PR fixes this bug adding `streamingTarget` prop to NewContentMessage, to make it possible to subscribe to the server peer by telling the final known state after the streaming and not the current one.

Fixes #2584 

### Testing Instructions
- Open the filestream demo https://jazz-filestream-git-fix-storage-streaming-gcmp.vercel.app/
- Open the network inspector
- Upload a file larger than 100Kb
- Wait for the full sync with the server
- Reload the page
- Check the WebSocket messages, there should no content messages going to the sync server

The difference is noticeable when compared the messages sent on https://file-upload.demo.jazz.tools/ using the same flow.

### CODE REVIEW

File: packages/cojson/src/coValue.ts [hunk 1]
```diff
@@ -18,7 +15,7 @@ export type CoID<T extends RawCoValue> = RawCoID & {
 export interface RawCoValue {
   /** The `CoValue`'s (precisely typed) `CoID` */
   id: CoID<this>;
-  core: AvailableCoValueCore;
+  core: CoValueCoreVerified;
```
Comment (gdorsi) [inline packages/cojson/src/coValue.ts:18]: Renamed because it isn't related to Available state, which requires also the CoValue deps, but only a CoValue with a VerifiedState

File: packages/cojson/src/storage/knownState.ts [hunk 2]
```diff
@@ -48,16 +49,30 @@ export class StorageKnownState {
...
+    if (isInSync(coValue.knownState(), this.getKnownState(id))) {
       return Promise.resolve();
     }
 
     const requests = this.waitForSyncRequests.get(id) || new Set();
     this.waitForSyncRequests.set(id, requests);
 
     return new Promise<void>((resolve) => {
-      requests.add({ knownState, resolve });
+      const knownState = coValue.knownState();
```
Comment (gdorsi) [inline packages/cojson/src/storage/knownState.ts]: Before the `waitForSync` was getting the initial `knownState` of the in-memory coValue and so not working when waiting from the content to be pulled from the storage

File: packages/cojson/src/sync.ts [hunk 3]
```diff
@@ -482,28 +485,38 @@ export class SyncManager {
...
+        msg.streamingTarget,
+      );
+
+      if (msg.streamingTarget) {
+        peer?.combineWith(msg.id, {
+          id: msg.id,
+          header: true,
+          sessions: msg.streamingTarget,
+        });
+      }
```
Comment (gdorsi) [inline packages/cojson/src/sync.ts:516]: Here we track how much content the peer has, and since we know that the other peer is going to stream content to us, we track the streamingTarget here.

File: tests/browser-integration/src/browserSync.test.ts [hunk 4]
```diff
@@ -182,9 +179,6 @@ describe("Browser sync", () => {
       AccountSchema: CustomAccount,
     });
 
-    // TODO: Wait for sync doesn't work on the IndexedDB storage peer as it just waits for the content to be pushed
-    await new Promise((resolve) => setTimeout(resolve, 500));
-
```
Comment (gdorsi) [inline tests/browser-integration/src/browserSync.test.ts:187]: Improved the API and stability around storage, so we can now remove these workarounds from the browser tests.

File: packages/cojson/src/coValueCore/verifiedState.ts [hunk 5]
```diff
@@ -336,6 +351,43 @@ export class VerifiedState {
...
+      const entries = Object.entries(this.streamingKnownState);
+      let outdated = true;
+
+      for (const [sessionID, txs] of entries) {
+        if ((knownState.sessions[sessionID as SessionID] ?? 0) < txs) {
+          newSessions[sessionID as SessionID] = txs;
+          outdated = false;
+        } else {
+          newSessions[sessionID as SessionID] = txs;
+        }
```
Comment (nrainhart) [inline packages/cojson/src/coValueCore/verifiedState.ts]: Nit:
```suggestion
        newSessions[sessionID as SessionID] = txs;
        if ((knownState.sessions[sessionID as SessionID] ?? 0) < txs) {
          outdated = false;
        }
```

File: packages/cojson/src/storage/knownState.ts (hunk 2 above)
Comment (nrainhart) [inline packages/cojson/src/storage/knownState.ts]: Nit: the result of `coValue.knownState()` could be extracted into a constant to avoid calling the method twice (here and in L53)

**Review by nrainhart — APPROVED** [review]
I've got very little context on jazz's architecture and abstractions, but I didn't notice any flagrant errors in this PR. Left only a few minor comments
